Lang:

  # Plugin language
  lang: en_us

  # Send messages to clients in their own language, if available
  client-lang: true



Options:

  # Plugin sends update notifications
  check-for-update: true

  # Defines the default size between the top parts of rows
  default-size-between-rows: 0.26

  # Defines a list of Unicode symbols to be converted within holo rows
  Symbols:

    "[X]": "\u2588"
    "[|]": "\u23B9"

  Link:

    # Defines whether the PlaceholderAPI link should be active
    placeholder-api: true

  # List of active feature flags (primarily for unofficial features for individual use)
  FeatureFlags: []