name: ${project.parent.name}
version: ${project.parent.version}
description: ${project.description}
authors: [Gecolay]
website: https://www.spigotmc.org/resources/121144
main: ${project.parent.groupId}.${project.parent.artifactId}Main
api-version: 1.19
folia-supported: true
softdepend: [PlaceholderAPI]

commands:

  gholo:

    usage: /<command>
    aliases: [holo]
    description: Holo command

  gholoreload:

    usage: /<command>
    aliases: [gholorl]
    description: Plugin reload command
    permission: GHolo.Reload



permissions:

  GHolo.*:
    default: op
    description: GHolo | Permissions
    children:
      GHolo.Holo: true
      GHolo.Update: true
      GHolo.Reload: true

  GHolo.Holo:
    default: op
    description: Holo command | Permission

  GHolo.Update:
    default: op
    description: Update notification | Permission

  GHolo.Reload:
    default: op
    description: Plugin reload command | Permission